title: Berliner Republik

email: info@die-berliner-republik.de
developer_email: amalcho97@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  German food at its best! Welcome to Berlin! Berliner Republik restaurant offers you great
  place to have a lunch with friends or family, celebrate a unique day for you as wedding and
  birthday or just go out for a sweet date with your new partner!
baseurl: "/Republik" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: "docs/"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - .gitignore
   - scss
   - gulpfile.js
   - package.json
   - package-lock.json
